Models/ErrorViewModel.cs
using System;

namespace ConsumeWebAPIs.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ConsumeWebAPIs.Models;

namespace ConsumeWebAPIs.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StudentAPIConsumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestfulAPIs_Asp.netCore.Models;

namespace ConsumeWebAPIs.Controllers
{
    public class StudentAPIConsumeController : Controller
    {
        private string LocalURL = "https://localhost:44351";
        public IActionResult Index()
        {
            List<StudentModel> Data = new List<StudentModel>();
            try
            {
                using (HttpClient Client = new HttpClient())
                {
                    Client.BaseAddress = new Uri(LocalURL);
                    Client.DefaultRequestHeaders.Accept.Clear();
                    Client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/jsons"));
                    HttpResponseMessage response = Client.GetAsync("/Student/GetAllStudents").Result;
                    Client.Dispose();
                    if (response.IsSuccessStatusCode)
                    {
                        string StringData = response.Content.ReadAsStringAsync().Result;
                        Data = JsonConvert.DeserializeObject<List<StudentModel>>(StringData);
                    }
                    else
                    {
                        TempData["Error"] = $"{response.ReasonPhrase}";
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["Exception"] = ex.Message; 
            }
            return View(Data);
        }

        public IActionResult AddStudent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddStudent(StudentModel StdModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (HttpClient Client = new HttpClient())
                    {
                        Client.BaseAddress = new Uri(LocalURL);
                        var Data = JsonConvert.SerializeObject(StdModel);
                        var ContentData = new StringContent(Data, Encoding.UTF8, "application/json");
                        if (StdModel.StudentID == 0)
                        {
                            HttpResponseMessage response = Client.PostAsync("/Student/AddStudent", ContentData).Result;
                            TempData["Success"] = "Record added successfully!";
                            // TempData["Success"] = response.Content.ReadAsStringAsync().Result;
                        }                      
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Model State is not valid");
                    return View(StdModel);
                }
            }
            catch (Exception Ex)
            {
                TempData["Exception"] = Ex.Message;
            }
            return RedirectToAction("Index");
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConsumeWebAPIs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ConsumeWebAPIs</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StudentAPIConsume" asp-action="Index">Students</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ConsumeWebAPIs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/StudentAPIConsume/AddStudent.cshtml
@model RestfulAPIs_Asp.netCore.Models.StudentModel
@{
    ViewData["Title"] = "AddStudent";
}

<div class="container">
    <div class="row">
        <div class="col-6 offset-3  border border-dark p-4 rounded rounded-top">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center text-primary">Add Student</h1>
                    <p class="text-center text-danger">@TempData["Exception"]</p>
                    <p class="text-center text-danger">@TempData["Error"]</p>
                </div>
                <div class="card-body">
                    <form method="post" asp-action="AddStudent">
                        <div class="form-group">
                            <label asp-for="RegistrationNo"></label>
                            <input type="text" asp-for="RegistrationNo" class="form-control" placeholder="Enter Registration No" />
                            <span class="text-danger" asp-validation-for="RegistrationNo"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Name"></label>
                            <input type="text" asp-for="Name" class="form-control" placeholder="Enter Student Name" />
                            <span class="text-danger" asp-validation-for="Name"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Gender"></label>
                            <select class="form-control" asp-for="Gender">
                                <option>--Select Gender--</option>
                                <option>Male</option>
                                <option>Female</option>
                                <option>Other</option>
                            </select>                          
                       <span class="text-danger" asp-validation-for="Gender"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="IsActive"></label>
                            <input type="checkbox" asp-for="IsActive" class="custom-checkbox"/>
                            <span class="text-danger" asp-validation-for="IsActive"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Submit" class="btn btn-sm btn-outline-success float-right" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial.cshtml"); }
}

Views/StudentAPIConsume/Index.cshtml
@model IEnumerable<RestfulAPIs_Asp.netCore.Models.StudentModel>
@{
    ViewData["Title"] = "Index";
    int Count = 1;
}

<div class="container">
    <div class="row">
        <div class="col-10 offset-1">
            <h1 class="text-center text-primary">Students Record</h1>
            <a class="btn btn-sm btn-success m-1" asp-controller="StudentAPIConsume" asp-action="AddStudent">Add</a>
            <p class="text-center text-success">@TempData["Exception"]</p>
            <p class="text-center text-danger">@TempData["Error"]</p>
            <p class="text-center text-danger">@TempData["Success"]</p>
            <table class="table table-bordered">
                <tr class="text-center">
                    <th>Sr. No</th>
                    <th>Registration No</th>
                    <th>Name</th>
                    <th>Gender</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
                @if (Model.Count() > 0)
                {
                    @foreach (var Std in Model)
                    {
                        <tr>
                            <td>@Count</td>
                            <td>@Std.RegistrationNo</td>
                            <td>@Std.Name</td>
                            <td>@Std.Gender</td>
                            <td>@Std.IsActive</td>
                            <td>
                                <a class="btn btn-sm btn-primary" asp-controller="StudentAPIConsume" asp-action="Edit" asp-route-id="@Std.StudentID">Edit</a>
                                <a class="btn btn-sm btn-danger" asp-controller="StudentAPIConsume" asp-action="Delete" asp-route-id="@Std.StudentID">Delete</a>
                                <a class="btn btn-sm btn-warning" asp-controller="StudentAPIConsume" asp-action="Details" asp-route-id="@Std.StudentID">Details</a>
                            </td>
                        </tr>
                        Count++;
                    }
                }
                else
                {
                    <tr class="text-center">
                        <td colspan="6">
                            <h2 class="text-warning bg-info">No Record Found</h2>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>
